/**
 * Build-time font fetcher (run manually, never at runtime).
 *
 * Downloads OFL-licensed WOFF2 files from Google Fonts and writes them to
 * src/ui/fonts/ plus src/ui/fonts.css, so the shipped site makes zero
 * third-party requests (PRD 9.1, NFR-1).
 *
 *   node scripts/fetch-fonts.mjs
 */
import { createHash } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const outDir = path.join(root, "src", "ui", "fonts");

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36";

const FAMILIES = [
  { id: "fraunces", query: "Fraunces:opsz,wght@9..144,600..700" },
  { id: "instrument-sans", query: "Instrument+Sans:wght@400;500;600" },
  { id: "jetbrains-mono", query: "JetBrains+Mono:wght@400;500;600" },
  { id: "noto-sans-devanagari", query: "Noto+Sans+Devanagari:wght@400;600" },
];

/** Keep only the latin (+ latin-ext) subsets so files stay small. */
const KEEP = /unicode-range:\s*U\+0000-00FF/i;

async function fetchText(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return res.text();
}

async function fetchBuffer(url) {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${url} -> ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

await mkdir(outDir, { recursive: true });

let css = `/* Generated by scripts/fetch-fonts.mjs — OFL licensed fonts, self-hosted.\n`;
css += `   Do not edit by hand; re-run the script to refresh. */\n\n`;

for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family.query}&display=swap`;
  const cssText = await fetchText(url);
  const blocks = cssText.split("@font-face").slice(1);
  for (const block of blocks) {
    if (!KEEP.test(block)) continue; // skip cyrillic/vietnamese/... subsets
    const srcMatch = block.match(/url\((https:[^)]+\.woff2)\)/);
    const rangeMatch = block.match(/unicode-range:\s*([^;]+);/);
    const weightMatch = block.match(/font-weight:\s*([^;]+);/);
    if (!srcMatch) continue;
    const buf = await fetchBuffer(srcMatch[1]);
    const digest = createHash("sha1").update(buf).digest("hex").slice(0, 8);
    // Google serves identical variable files per weight; dedupe by content.
    const file = `${family.id}-${digest}.woff2`;
    await writeFile(path.join(outDir, file), buf);
    const weight = (weightMatch?.[1] ?? "400").trim();
    css += `@font-face {\n`;
    css += `  font-family: "${family.id}";\n`;
    css += `  font-style: normal;\n`;
    css += `  font-weight: ${weight};\n`;
    css += `  font-display: swap;\n`;
    css += `  src: url("./fonts/${file}") format("woff2");\n`;
    if (rangeMatch) css += `  unicode-range: ${rangeMatch[1].trim()};\n`;
    css += `}\n\n`;
    console.log(`saved ${file} (${buf.length} bytes) weight=${weight}`);
  }
}

await writeFile(path.join(root, "src", "ui", "fonts.css"), css);
console.log("wrote src/ui/fonts.css");
